name: Levelborder
version: '${project.version}'
main: de.shockbase.levelborder.Levelborder
api-version: 1.18
depend: [ CoreProtect, WorldBorderAPI ]
authors: [ shockbase ]
description: World size depends on player level
website: https://shockbase.de
commands:
  lb:
    description: '/lb reset will kick you and delete all your data from this server!'
    usage: '/lb reset'
